CREATE TABLE `books` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `author` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci;